<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>

    <div class="field regulation">
        <label for="cpf" class="label">
            <span>
                <?php /* @escapeNotVerified */ echo __('CPF') ?>
            </span>
        </label>
        <div class="control">
            <input
                type="text"
                name="cpf"
                id="cpf"
                title="<?php /* @escapeNotVerified */ echo __('CPF') ?>"
                class="input-text"
                data-validate="{required:false}">
        </div>
    </div>
    <div class="field regulation">
        <label for="rg" class="label">
            <span>
                <?php /* @escapeNotVerified */ echo __('RG') ?>
            </span>
        </label>
        <div class="control">
            <input
                    type="text"
                    name="rg"
                    id="rg"
                    title="<?php /* @escapeNotVerified */ echo __('RG') ?>"
                    class="input-text"
                    data-validate="{required:false}">
        </div>
    </div>

</fieldset>